### ISSUE TITLE
What's the format of your wig file?

### ISSUE THREAD

**Issue by xueweireally** [chedinlab/DRIPc#2]
Hi,
The wig file in you **_wig2fa.pl_** is a single type variableStep wig file, how do you generate this format wig file? 
I used this pipeline to generate wig fileas below, but it doesn't work with _**wig2fa.pl**_.
genomeCoverageBed -> bedGraphToBigWig -> bigWigToWig

Could you show me your pipeline, my email is **xuewei906@hotmail.com**. Thanks.

Thanks,
Wei

**Comment by arrajpur** [comment]
Hi Wei,

Your pipeline produces a file of the format

chromosome TAB start TAB end TAB value
chromosome TAB start TAB end TAB value
...

Whereas wig2fa.pl expects a file of format:

variableStep chrom=CHROMOSOME span=SPAN
start_position TAB value
start_position TAB value
...

bigWigToWig just uncompresses the .bw file you input, it does not actually convert from bedgraph format to wig format. You will need to write a bedgraph to wig conversion script. 

I have a rough script that will do this conversion if you can't get it to work, but it was intended for personal use and not the most user-friendly.

Aparna

**Comment by cpstgermain** [comment]
what happens if your NOPEAK.fasta and PEAK.fasta are all N's? did i input the wrong chromosomal postions?

hi!!!! it's commodore btw...

**Comment by arrajpur** [comment]
Hey Commodore!

What coordinates are you inputting for PEAK and NOPEAK? There's two main possibilities: the wig2fa.pl isn't finding the correct sequences in your input fasta file even if they are there (potentially an indexing problem or format problem), or your regions are not present in that file.

**Comment by cpstgermain** [comment]
Hey!!

So I went through my customfasta file and it is all N's. The .clean.wig.norm file looks kinda the same as the example stuff we went through together. So much easier while you were here...

cpstgerm@crick:~/hmm$ head RNAPNTChIP20170113.clean.wig.norm
track type=wiggle_0 name="RNAPNT.wig" description="RNAPNT.wig"
variableStep chrom=chr1 span=199
3000600	1.66666666666667
3000800	5
3001000	1.66666666666667
3001200	1.66666666666667
3001400	1.66666666666667
3001800	1.66666666666667
3002200	1.66666666666667
3004400	1.66666666666667
cpstgerm@crick:~/hmm$

**Comment by YichaoOU** [comment]
how to create this variableStep wig file?

Thanks,
Yichao
