### ISSUE TITLE
Can it be used to call DRIP peaks for Plants ?　　

### ISSUE THREAD

**Issue by yuaner90** [chedinlab/DRIPc#3]

**Comment by arrajpur** [comment]
These models should work for DRIP performed on plants. However, as it has not been tested before with this specific organism, I would recommend you try this model and also some other peak callers and test which one works best.

**Comment by yuaner90** [comment]
Thanks very much, I test it in rice, my results conclude three types peaks, Noisy_Broad peaks,and Noisy_Med peaks and Sparse_Sharp peaks. when I saw data in Genome browser, I found the Noisy_Med peaks are weak, so I suggest if will be higher false positive among this type peaks. When I peak calling, the software whether provide a parameter for control or Input ?

**Comment by arrajpur** [comment]
No there is no parameter for control and input. What you can do is use the same model file to call peaks on both your sample and input separately, then remove all peaks in your sample peakset that overlap with peaks in the input.
