### ISSUE TITLE
what's the difference between DRIP.hmm and DRIPc.hmm?

### ISSUE THREAD

**Issue by yuaner90** [chedinlab/DRIPc#4]
Hi,
   when I used the  DRIP pipline  for peak calling, I got my peaks with by DRIP.hmm file , but when I used DRIPc pipline and DRIPc.hmm , I encounter an issue "Segmentation fault (core dumped)", and  my reads with different sizes after trimmed, is it ok for peak calling ? Could you explain my question ?

**Comment by arrajpur** [comment]
The DRIPc pipeline is intended only for DRIPc experimental data. It is not intended for use on DRIP data.  

The read lengths should not matter. The segmentation fault is produced by the stochhmm software that is used to run the models provided here. I would recommend that you carefully check your input files to ensure that they conform to the stochhmm specs, and check your parameters to stochhmm.
